export enum NotificationTypes {
  REBOOK_RESERVATION,
  UPDATE_RESERVATION,
  CANCEL_RESERVATION,
  BOOK_RESERVATION,
  DISLIKE_LISTING,
  LIKE_LISTING,
  REVIEW_RESERVATION,
  COMPLETE_RESERVATION,
}
